### PR TITLE
[FIX] workloadspread yaml format error

### PR DESCRIPTION
**Pull request by ls-2018**

### CODE REVIEW

**Review by furykerry — COMMENTED** [review]
/lgtm

**Comment by furykerry** [comment]
@ls-2018 thanks for you continuous effort to correct kruise documentation errors, if you have any tools to detect such errors we can integrate into the repository pipeline

**Review by furykerry — COMMENTED** [review]
/approve

**Comment by ls-2018** [comment]
no tools. It's all manual😂

**Pull request merged**
