### PR TITLE
typo fix: dependencies

### PR DESCRIPTION
**Pull request by changren-wcr**

### CODE REVIEW

**Comment by FillZpp** [comment]
LGTM, thanks. The DCO failed, please sign yourself by `git commit --amend -s` and then force push again. @changren-wcr

**Comment by changren-wcr** [comment]
> LGTM, thanks. The DCO failed, please sign yourself by `git commit --amend -s` and then force push again. @changren-wcr

sign-off message is added to commit message

**Review by FillZpp — APPROVED** [review]
/lgtm

**Pull request merged**
